#ifndef ELIXIR_DATA_H
#define ELIXIR_DATA_H

#include <vector>
#include <unordered_set>

namespace elixir {

  using namespace std;

  class Data {
    int fromNodeKey;

    // data generated by a single node
    vector<void *> data;

    // Map: toNodeKey -> the is satisified
    unordered_set<int> toNodeKeys;
  };
}

#endif /* ELIXIR_DATA_H */
