#ifndef ELIXIR_DATA_H
#define ELIXIR_DATA_H

#include <vector>
#include <unordered_set>

namespace elixir {

  using namespace std;

  class Data {
    int fromNodeKey;

    // data generated by a single node
    vector<void *> data;

    // toNodeKey (children)
    vector<int> toNodeKeys;

  public:
    Data(vector<int> &children) {

    }
  };
}

#endif /* ELIXIR_DATA_H */
