#ifndef ELIXIR_DATA_H
#define ELIXIR_DATA_H

#include <vector>
#include <unordered_map>
#include <string>

namespace elixir {

  using namespace std;

  class Data {
    int fromNodeKey;

    // toNodeKey (children)
    vector<int> toNodeKeys;

  public:
    Data(unordered_map<string, void *> data,
         int fromNodeKey,
         vector<int> children)
      : fromNodeKey(fromNodeKey),
        toNodeKeys(children),
        data(data) {}

    // data generated by a single node
    unordered_map<string, void *> data;
  };
}

#endif /* ELIXIR_DATA_H */
